### ISSUE TITLE
Make haskelldb version the same at tomjaguarpaw/haskelldb

### ISSUE THREAD

**Issue by dbp** [karamaan/karamaan-opaleye#81]
Having to modify the code after checking out is annoying! 

I would like to be able to clone opaleye, plankton, product-profuntors, and tom's version of haskelldb and be able to have things work. 

I don't see any particular reason why the version in the cabal file at tomjaguarpaw/haskelldb is 2.2.3, rather than  2.2.2.0.0.0.3 (especially as the advice is to use  that specific repository).

**Comment by tomjaguarpaw** [comment]
OK, well I added an `opaleye` branch to my `haskelldb` which will always have a version number that matches the requirement in `opaleye/dev`.  Adding the version number to `tomjaguarpaw/haskelldb/master` is less straightforward because of how we use `haskelldb` internally.

https://github.com/tomjaguarpaw/haskelldb/tree/opaleye

Hope that helps.

**Comment by dbp** [comment]
Good enough for me!
